RaiblocksSignService:
    Db:
        LogsConnString:
            settings-key: "RaiblocksSignService-LogsConnString"
            types:
                - AzureBlobStorage
                - Tag

MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl 

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName